teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE001*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE002*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE003*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE004*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE005*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE006*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE007*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE008*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE009*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE010*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE011*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE012*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE013*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE014*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE015*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE016*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE017*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE018*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE019*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE020*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE021*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE022*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE023*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE024*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE025*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE026*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE027*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE028*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE029*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE030*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE031*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE032*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE033*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE034*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE035*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE036*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE037*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE038*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE039*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE040*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE041*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE042*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE043*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE044*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE045*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE046*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE047*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE048*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE049*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE050*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE051*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE052*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE053*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE054*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE055*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE056*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE057*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE058*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE059*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE060*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE061*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE062*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE063*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE064*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE065*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE066*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE067*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE068*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE069*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE070*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE071*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE072*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE073*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE074*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE075*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE076*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE077*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE078*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE079*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE080*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE081*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE082*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE083*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE084*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE085*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE086*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE087*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE088*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE089*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE090*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE091*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE092*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE093*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE094*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE095*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE096*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE097*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE098*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE099*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE100*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE101*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE102*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE103*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE104*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE105*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE106*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE107*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE108*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE109*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE110*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE111*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE112*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE113*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE114*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE115*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE116*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE117*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE118*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE119*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE120*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE121*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE122*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE123*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE124*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE125*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE126*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE127*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE128*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE129*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE130*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE131*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE132*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE133*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE134*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE135*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE136*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE137*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE138*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE139*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE140*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE141*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE142*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE143*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE144*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE145*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE146*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE147*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE148*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE149*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE150*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE151*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE152*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE153*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE154*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE155*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE156*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE157*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE158*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE159*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE160*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE161*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE162*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE163*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE164*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE165*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE166*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE167*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE168*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE169*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE170*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE171*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE172*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE173*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE174*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE175*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE176*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE177*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE178*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE179*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE180*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE181*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE182*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE183*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE184*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE185*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE186*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE187*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE188*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE189*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE190*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE191*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE192*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE193*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE194*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE195*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE196*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE197*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE198*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE199*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE200*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE201*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE202*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE203*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE204*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE205*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE206*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE207*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE208*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE209*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE210*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE211*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE212*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE213*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE214*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE215*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE216*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE217*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE218*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE219*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE220*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE221*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE222*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE223*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE224*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE225*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE226*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE227*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE228*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE229*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE230*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE231*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE232*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE233*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE234*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE235*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE236*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE237*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE238*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE239*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE240*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE241*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE242*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE243*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE244*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE245*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE246*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE247*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE248*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE249*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE250*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE251*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE252*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE253*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE254*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE255*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE256*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE257*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE258*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE259*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE260*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE261*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE262*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE263*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE264*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE265*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE266*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE267*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE268*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE269*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE270*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE271*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE272*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE273*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE274*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE275*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE276*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE277*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE278*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE279*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE280*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE281*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE282*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE283*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE284*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE285*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE286*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE287*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE288*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE289*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE290*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE291*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE292*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE293*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE294*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE295*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE296*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE297*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE298*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE299*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE300*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE301*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE302*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE303*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE304*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE305*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE306*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE307*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE308*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE309*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE310*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE311*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE312*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE313*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE314*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE315*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE316*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE317*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE318*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE319*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE320*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE321*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE322*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE323*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE324*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE325*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE326*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE327*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE328*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE329*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE330*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE331*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE332*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE333*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE334*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE335*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE336*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE337*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE338*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE339*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE340*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE341*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE342*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE343*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE344*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE345*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE346*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE347*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE348*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE349*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE350*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE351*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE352*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE353*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE354*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE355*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE356*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE357*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE358*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE359*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE360*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE361*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE362*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE363*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE364*.m??
teqc -phc -O.dec 30s -O.r CJVC -O.mo SITE -O.mn SITE -O.pe 0 0 0 +C2 +obs + -tbin 1d SITE SITE365*.m??