setlocal enabledelayedexpansion
for %%f in (F1_?????0.CRD) do (
findstr /V "ABMF ABPO ADE1 ADE2 ADIS AJAC ALBH ALGO ALRT AMC2 AOML AREQ AREV ARTU ASC1 AUCK BADG BAHR BAKO BARH BHR1 BHR2 BILI BJCO BJFS BJNM BOR1 BRAZ BREW BRFT BRMU BRST BRUS BRUX BSHM BUCU CAGL CAGZ CAS1 CEDU CFAG CHAN CHAT CHPI CHTI CHUM CHUR CKIS CNMR COCO CONX CONZ CRAO CRO1 DARR DAV1 DAVR DGAR DGAV DRAG DRAO DUBO DUM1 EBRE EISL FAA1 FAIR FALK FLIN FLRS FORT FUNC GANP GLPS GLSV GMAS GODE GODZ GOL2 GOLD GOUG GRAS GRAZ GUAM GUAO GUAT HARB HERS HERT HLFX HNLC HOB2 HOFN HOLB HOLM HRAO HYDE IISC INVK IQAL IRKM IRKT ISPA JOZE KARR KAT1 KELY KERG KIRI KIRU KIT3 KOKB KOKV KOSG KOUR KRGG KWJ1 LAUT LHAS LHAZ LMMF LPAL LPGS LROC MAC1 MAL2 MALI MAR6 MAS1 MAT1 MATE MAUI MAW1 MBAR MCM4 MDO1 MDVJ MDVO MEDI METS MKEA MOBS MONP MQZG MR6G NAIN NAMA NANO NAUR NICO NIST NISU NIUM NKLG NLIB NNOR NOT1 NOUM NRC1 NRIL NRMD NRMG NURK NYA1 NYAL OHI2 OHI3 OHIG OHIX ONSA OS0G OSN1 OSN2 OUS2 PARC PDEL PERT PIE1 POHN POL2 POLV POTS PRDS PRE1 PRE2 QAQ1 QIKI QUIN RABT RAMO RCMN RECF RESO REUN RIGA RIO2 RIOG SALU SANT SAVO SCH2 SCOR SCUB SFER SHAO SOFI STHL STJO SUTH SUTM SUTV SUWN SYDN SYOG TAEJ TAH1 TAH2 TASH TCMS TEHN THTI THU2 THU3 TID1 TID2 TIDB TIXG TIXI TLSE TOUL TOW2 TRAB TRO1 TROM TSKB TUVA TWTF UFPR UNB3 UNBJ UNBN UNBT UNSA USN3 USN4 USN5 USNO USUD UZHL VACS VESL VNDP WES2 WHIT WILL WIND WSRT WTZR WUHN XMIS YAKT YAR1 YAR2 YEBE YELL YIBL YSSK ZAMB ZECK ZIM2 ZIM3 ZIMM" %%~nf%%~xf > %%~nf%%~xfA
)
mkdir F1CRD
move F1_?????0.CRD F1CRD
for %%a in (*F1_*) do (
  set file=%%a
  ren "!file!" "!file:F1_=FN!"
)
ren *.CRDA *.CRD